### ISSUE TITLE
idseq-bench availability

### ISSUE THREAD

**Issue by zztin** [chanzuckerberg/czid-workflows#105]
Hi, 

I have landed here by reading your publication (IDseq). I am wondering if the idseq-bench module can still be found somewhere open sourced? And can you provide some instruction how do I simulate sequencing data with pathogen and host reads? The original repo provided in the manuscript is removed (https://github.com/chanzuckerberg/idseq-bench). It would be helpful if it still exist somewhere. 

Best, 
Li-Ting

**Comment by rzlim08** [comment]
Hi Li-Ting, 

Sorry for the very late response; the repo should be public again. If you format the `config.yaml` file to include both the pathogen and host reference genomes, you should be able to simulate data with both.

**Comment by zztin** [comment]
Hi rzlim08,

Great! Thanks for the update!
