### ISSUE TITLE
short-read-mngs local_driver example not working due to erroneous variable names

### ISSUE THREAD

**Issue by AIRibone** [chanzuckerberg/czid-workflows#323]
Hi, I have just installed the czid-workflows in a local server and was trying the examples.

I succesfully ran the short-read-mngs "viral" example that uses the option file: workflows/short-read-mngs/test/local_test_viral.yml

But when I tried the full pipeline example (czid-workflows/workflows/short-read-mngs/test/local_test.yml) I found several that seem to arise from missing or wrongfully named variables.

```
miniwdl run czid-workflows/workflows/short-read-mngs/local_driver.wdl \
    docker_image_id=ghcr.io/chanzuckerberg/czid-workflows/czid-short-read-mngs-public \
    fastqs_0=czid-workflows/workflows/short-read-mngs/test/norg_6__nacc_27__uniform_weight_per_organism__hiseq_reads__v6__R1.fastq.gz \
    fastqs_1=czid-workflows/workflows/short-read-mngs/test/norg_6__nacc_27__uniform_weight_per_organism__hiseq_reads__v6__R2.fastq.gz \
    -i czid-workflows/workflows/short-read-mngs/test/local_test.yml --verbose

```

```
2024-02-06 20:49:27.111 miniwdl-run no configuration file found

check JSON input; unknown input/output: host_filter.star_genome

```

These variables were present in the local_test.yml file yet non-expected by short-read-mngs pipeline:

- host_filter.star_genome
- host_filter.gsnap_genome
- host_filter.human_star_genome

Also, the error log says "no configuration file found" which is false, the configuration file is found, but there are errors in it.

**Comment by YZLong** [comment]
Hi AIRibone,
I have got same problem in recent days. I have tried to commented out the three file you mentioned in the local_test.yml. the miniwdl return the error like this:
```
missing required inputs for czid_short_read_mngs: host_filter.hisat2_index_tar,
host_filter.kallisto_idx, host_filter.human_hisat2_index_tar
```
I found the mentioned 3 paramenters exist in local_test_viral.yml.

I am wondering if you have any new solution to this problem.
Best regards.

**Comment by YZLong** [comment]
hi there,
I found the 3 file name in the file(https://github.com/chanzuckerberg/czid-workflows/blob/main/workflows/short-read-mngs/host_filter_defaults.yml) of the repo, currently testing the command now.

**Comment by rzlim08** [comment]
Sorry for the late response, thanks for the heads up! You're right, we changed our host filtering step but didn't change the test yaml file. I'll make sure this gets fixed.
