### ISSUE TITLE
Defining Output Folder Name With the Name of Our Choice

### ISSUE THREAD

**Issue by Samiah-Kanwar** [chanzuckerberg/czid-workflows#33]
Hi @rzlim08, while running CZID consensus genome pipeline locally, the name of output folder always starts with date and time followed by "_consensus_genome" for example  `20220314_161758_consensus_genome`. Is there any way to generate folder name of our choice instead of timestamp-named directory ?
I have explored the option of `-d` in `miniwdl run` but it creates additional directory under which timestamp-named sub-directory is created.

**Comment by mlin** [comment]
@Samiah-Kanwar `miniwdl run -d desired/folder/.` should use that folder exactly (note the trailing slashdot)

**Comment by Samiah-Kanwar** [comment]
Okay got this, Thanks!
