### ISSUE TITLE
Mapping host-specific reads

### ISSUE THREAD

**Issue by stecata** [chanzuckerberg/czid-workflows#351]
Hi there,

I apologise if this is not applicable to the Issues section. My group and I are currently using the metagenomics pipeline for Illumina sequencing on CZ ID. We mainly work with wildlife specimens in resource-scarce settings and CZ ID is proving fantastic. My issue is trying to include host-specific reads into the final output. At the beginning of the workflow I state that the host is unknown but I still do not get any reads mapping to potential hosts (the most recently data I uploaded originated from wild Lemniscomys and Mastomys mice).

Is there a solution or something I could change in the parameters? Or the pipeline is exclusively designed towards potential pathogens with no read mapping against non-human host genomes?

Thank you so much and looking forward to your reply.

Stefano

**Comment by rzlim08** [comment]
Hi Stefano, you would probably get a better answer by emailing: help@czid.org. Thanks!
